#healenium properties
recovery-tries = 1
score-cap = .6
heal-enabled = true
serverHost = localhost
serverPort = 7878
imitatorPort = 8000

#ReportPortal properties
#Update report title
allure.customTitle=SOF Revamp Automation
#keep history of previous test runs
allure.accumulateHistory=false
#open allure report after execution
allure.automaticallyOpen=false
#by default keeps old html allure reports and if false it will keep only last run report
allure.accumulateReports=true