status = error
name = PropertiesConfig

# Console Appender
appender.console.type = Console
appender.console.name = STDOUT
appender.console.layout.type = PatternLayout
appender.console.layout.disableAnsi = false
#appender.console.layout.pattern = [%p] %d{HH:mm:ss} %c{1} - %m%n
appender.console.layout.pattern = [%highlight{%p}{FATAL=red blink, ERROR=red bold, WARN=yellow bold, INFO=cyan, DEBUG=green, TRACE=blue}] %d{HH:mm:ss} %c{1} - %m%n
appender.console.filter.threshold.type = ThresholdFilter
appender.console.filter.threshold.level = info

# File Appender
appender.file.type = File
appender.file.name = LOGFILE
appender.file.fileName = target/logs/log4j.log
appender.file.layout.type = PatternLayout
appender.file.layout.pattern = [%-5level] %d{yyyy-MM-dd HH:mm:ss.SSS} [%t] %c{1} - %msg%n
appender.file.filter.threshold.type = ThresholdFilter
appender.file.filter.threshold.level = debug

# Root Logger
rootLogger.level = debug
rootLogger.appenderRefs = STDOUT, LOGFILE
rootLogger.appenderRef.STDOUT.ref = STDOUT
rootLogger.appenderRef.LOGFILE.ref = LOGFILE

# Set specific logger level for org.apache.http.impl.client
logger.httpclient.name = org.apache.http.impl.client
logger.httpclient.level = warn

# Healenium Logger
logger.healenium.name = io.github.healenium
logger.healenium.level = debug
logger.healenium.additivity = true

# Selenium HTTP Logger
logger.seleniumws.name = org.openqa.selenium.remote.http.WebSocket
logger.seleniumws.level = error
logger.seleniumws.additivity = false
logger.seleniumws.appenderRefs = STDOUT, LOGFILE
logger.seleniumws.appenderRef.STDOUT.ref = STDOUT
logger.seleniumws.appenderRef.LOGFILE.ref = LOGFILE